import streamlit as st
x=st.checkbox('Sim')
st.write(x)
st.title(x)
st.button('Clique')
respgenero=st.radio('Selecione seu gênero',['Masculino','Feminino'])
respgen=st.selectbox('Selecione seu gênero',['Masculino','Feminino'])
respdep=st.multiselect('Escolha um departamento',['DESIN','DECAR','DIPAS'])
respsent=st.select_slider('Selecione uma resposta',['Ruim','Bom','Excelente'])
repnum=st.slider('Selecione um número',0,100)
respnume=st.number_input('Selecione um número',0,10)
st.write(respgenero)
st.write(respgen)
st.write(respdep)
st.write(respsent)
st.write(repnum)
st.write(respnume)
st.text_input('Endereço de e-mail')
st.date_input('Data de viagem')
st.time_input('Tempo de escola')
st.text_area('Descrição')
st.file_uploader('Atualize uma foto')
st.color_picker('Escolha sua cor favorita')
if respnume==10:
  st.success("Você conseguiu!")
if respnume==11:
  st.error("Erro!")
if respnume==0:
  st.warning("Advertência")
if respnume==5:
  st.info("Esta é uma informação")
